#!/usr/bin/with-contenv bash

# create symlinks
symlinks=( \
/var/www/html/config.php \
/var/www/html/themes.local \
/var/www/html/plugins.local \
/var/www/html/cache \
/var/www/html/lock \
/var/www/html/feed-icons
)

for i in "${symlinks[@]}"; do
	[[ "$(basename "$i")" == "config.php" && ! -L "$i" ]] && \
		ln -s /config/"$(basename "$i")" "$i"
	[[ -e "$i" && ! -L "$i" && -e /config/"$(basename "$i")" ]] && \
		rm -Rf "$i" && \
		ln -s /config/"$(basename "$i")" "$i"
	[[ -e "$i" && ! -L "$i" ]] && \
		mv "$i" /config/"$(basename "$i")" && \
		ln -s /config/"$(basename "$i")" "$i"
done

# translate legacy variables
printf "${DB_TYPE}" > /var/run/s6/container_environment/TTRSS_DB_TYPE
printf "${DB_HOST}" > /var/run/s6/container_environment/TTRSS_DB_HOST
printf "${DB_USER}" > /var/run/s6/container_environment/TTRSS_DB_USER
printf "${DB_NAME}" > /var/run/s6/container_environment/TTRSS_DB_NAME
printf "${DB_PASS}" > /var/run/s6/container_environment/TTRSS_DB_PASS
printf "${DB_PORT}" > /var/run/s6/container_environment/TTRSS_DB_PORT
printf "${MYSQL_CHARSET}" > /var/run/s6/container_environment/TTRSS_MYSQL_CHARSET
printf "${SELF_URL_PATH}" > /var/run/s6/container_environment/TTRSS_SELF_URL_PATH
printf "${SINGLE_USER_MODE}" > /var/run/s6/container_environment/TTRSS_SINGLE_USER_MODE
printf "${SIMPLE_UPDATE_MODE}" > /var/run/s6/container_environment/TTRSS_SIMPLE_UPDATE_MODE
printf "${PHP_EXECUTABLE}" > /var/run/s6/container_environment/TTRSS_PHP_EXECUTABLE
printf "${LOCK_DIRECTORY}" > /var/run/s6/container_environment/TTRSS_LOCK_DIRECTORY
printf "${CACHE_DIR}" > /var/run/s6/container_environment/TTRSS_CACHE_DIR
printf "${ICONS_DIR}" > /var/run/s6/container_environment/TTRSS_ICONS_DIR
printf "${ICONS_URL}" > /var/run/s6/container_environment/TTRSS_ICONS_URL
printf "${AUTH_AUTO_CREATE}" > /var/run/s6/container_environment/TTRSS_AUTH_AUTO_CREATE
printf "${AUTH_AUTO_LOGIN}" > /var/run/s6/container_environment/TTRSS_AUTH_AUTO_LOGIN
printf "${FORCE_ARTICLE_PURGE}" > /var/run/s6/container_environment/TTRSS_FORCE_ARTICLE_PURGE
printf "${SPHINX_SERVER}" > /var/run/s6/container_environment/TTRSS_SPHINX_SERVER
printf "${SPHINX_INDEX}" > /var/run/s6/container_environment/TTRSS_SPHINX_INDEX
printf "${ENABLE_REGISTRATION}" > /var/run/s6/container_environment/TTRSS_ENABLE_REGISTRATION
printf "${REG_NOTIFY_ADDRESS}" > /var/run/s6/container_environment/TTRSS_REG_NOTIFY_ADDRESS
printf "${REG_MAX_USERS}" > /var/run/s6/container_environment/TTRSS_REG_MAX_USERS
printf "${SESSION_COOKIE_LIFETIME}" > /var/run/s6/container_environment/TTRSS_SESSION_COOKIE_LIFETIME
printf "${SMTP_FROM_NAME}" > /var/run/s6/container_environment/TTRSS_SMTP_FROM_NAME
printf "${SMTP_FROM_ADDRESS}" > /var/run/s6/container_environment/TTRSS_SMTP_FROM_ADDRESS
printf "${DIGEST_SUBJECT}" > /var/run/s6/container_environment/TTRSS_DIGEST_SUBJECT
printf "${CHECK_FOR_UPDATES}" > /var/run/s6/container_environment/TTRSS_CHECK_FOR_UPDATES
printf "${ENABLE_GZIP_OUTPUT}" > /var/run/s6/container_environment/TTRSS_ENABLE_GZIP_OUTPUT
printf "${PLUGINS}" > /var/run/s6/container_environment/TTRSS_PLUGINS
printf "${LOG_DESTINATION}" > /var/run/s6/container_environment/TTRSS_LOG_DESTINATION

# permissions
chown -R abc:abc \
	/config \
	/var/www/html/

# even if using environment, tt-rss needs config.php to at least exist
touch config/config.php
